---
title: "HW3"
author: "Yaling Hong"
date: "2022/10/17"
output: github_document
---


```{r,collapse=TRUE}
library(dplyr)
library(nycflights13)
library(ggplot2)
library(maps)
library(tidyr)
```


1

```{r}
avg_delay=flights%>%
  group_by(dest)%>%
  summarise(avg_delay=mean(arr_delay,na.rm=T))
avg_delay=avg_delay[complete.cases(avg_delay),]
airport=airports%>%
  select(faa,lat,lon)
colnames(airport)=c("dest","lat","lon")
data=right_join(airport,avg_delay)
data=data[complete.cases(data),]
ggplot(data,aes(lon,lat))+
  borders("state")+
  geom_point(aes(colour=avg_delay))+
  coord_quickmap()+
  xlab("longitude")+
  ylab("latitude")+
  ggtitle("Spatial Distribution of Average Delay for Each Airport")
```

2

```{r}
colnames(airport)=c("origin","lat","lon")
org=flights%>%
  left_join(airport,by="origin")
org_names=colnames(org)
org_names[length(org_names)]="origin_lon"
org_names[length(org_names)-1]="origin_lat"
colnames(org)=org_names
colnames(airport)[1]="dest"
dest=flights%>%
  select(dest)%>%
  left_join(airport,by="dest")
dest_names=colnames(dest)
dest_names[3]="dest_lon"
dest_names[2]="dest_lat"
colnames(dest)=dest_names
dest_lon=dest$dest_lon
dest_lat=dest$dest_lat
flight=org%>%
  mutate(dest_lon=dest_lon,dest_lat=dest_lat)
head(flight)
```


3

From the plot below we cannot conclude that there is a relationship between the age of the plane and delays. Although some new planes tend to have higher delays, they also provide more flights. We cannot tell whether the carrier assign more flights to them because they are young.

```{r}
delay_tail=flights%>%
  group_by(tailnum)%>%
  summarise(avg_delay=mean(arr_delay,na.rm=T))
delay_tail=delay_tail[complete.cases(delay_tail),]
age=planes%>%
  select(tailnum,year)
df=left_join(delay_tail,age,by="tailnum")
df=df[complete.cases(df),]
ggplot(df,aes(year,avg_delay))+
  geom_point()+
  xlab("age")+
  ylab("average delay")+
  ggtitle("Average Delay against Age of Planes")
```

